project:
  type: website

website:
  title: "Chuck Horgan"
  reader-mode: true
  navbar:
    search: true
    left:
      - text: "Home"
        file: home.qmd
      - text: "About"
        file: about/about.qmd
      - text: "Blog"
        file: blog/blog.qmd
      - text: "Code Snippets"
        file: snippets/snippets.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    max-width: "1000px"

editor: source

