project:
  type: website

website:
  title: "Chuck Horgan"
  reader-mode: true
  navbar:
    search: true
    left:
      - text: "Home"
        file: home.qmd
      - text: "About"
        file: about/about.qmd
      - text: "How-To"
        file: howto/howto.qmd
      - text: "Code Snippets"
        file: snippets/snippets.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

editor: source

