---
title: RStudio Desktop on Ubuntu
author: Chuck Horgan
date: '2022-06-21'
categories:
  - R
  - RStudio
  - Ubuntu
  - Linux
---

# Install R

- The main instructions are [here](https://cran.rstudio.com/bin/linux/ubuntu/README.html), but I have summarized them for R 4.0 below.

- Add entry to sources.list for R 4.0. Save and exit nano editor with `C-s` `C-x`.

```bash
sudo nano /etc/apt/sources.list
# add the following line to the end of the file
deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/
```

- Add the public key to the local keyfile. Without this step, you will get a "PUBLIC KEY NOT FOUND" error.

```bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
```

- Install base R system. Check specific instructions to [support multiple versions](https://docs.rstudio.com/resources/install-r/) (if applicable).

```bash
sudo apt-get update
sudo apt-get install r-base
```

- Install dev, needed for use of `install.packages()`.

```bash
sudo apt-get install r-base-dev
```

# Install RStudio

- Again, the main instructions are [here](https://rstudio.com/products/rstudio/download-server/debian-ubuntu/) (scroll down to "Install for Debian 10 / Ubuntu 18 / Ubuntu 20"), but I have summarized them below. 

- Import public code-signing key. As described [here](https://rstudio.com/code-signing/), this is necessary to install RStudio.

```bash
gpg --keyserver keys.gnupg.net --recv-keys 3F32EE77E331692F
```

- Download RStudio from the [main download page](https://rstudio.com/products/rstudio/download/) with `wget`. Scroll down to "All Installers", find the "Ubuntu 18/Debian 10" OS, right-click on the download file, and copy link address. As of November 2020, it is *https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.3.1093-amd64.deb*, so that is used in the following example.

```bash
cd ~/Downloads
wget https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.3.1093-amd64.deb
```

- Verify key on download. It should say "GOODSIG". Install the `dpkg-sig` package if necessary. As of November 2020, the installer file is *rstudio-1.3.1093-amd64.deb*, so that is used in the following example.

```bash
sudo apt-get install dpkg-sig
dpkg-sig --verify rstudio-1.3.1093-amd64.deb
```

- Install RStudio.

```bash
# assumes you are in Downloads/ folder
sudo apt install ./rstudio-1.3.1093-amd64.deb
```

- Launch with `rstudio`, or open in the "Application Finder"!
